import { StyleSheet } from '@react-pdf/renderer';
export const styles = StyleSheet.create({
  page: {
    backgroundColor: '#F7FBFA',
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
  },
  fullWidth: {
    width: '100%',
  },
  cover: {
    minHeight: '100%',
    backgroundColor: '#FFFFFF',
    paddingTop: 56,
    paddingRight: 48,
    paddingBottom: 56,
    paddingLeft: 48,
    borderBottom: '6px solid #1AA69A',
    justifyContent: 'space-between',
    position: 'relative',
    overflow: 'hidden',
  },
  topWave: {
    position: 'absolute',
    top: -120,
    left: -80,
    width: 320,
    height: 320,
    border: '2px solid #9ED7CF',
    borderRadius: 180,
  },
  topWaveInner: {
    position: 'absolute',
    top: -90,
    left: -50,
    width: 260,
    height: 260,
    border: '1px solid #BEE7E1',
    borderRadius: 140,
  },
  bottomBlob: {
    position: 'absolute',
    bottom: -110,
    left: -90,
    width: 240,
    height: 240,
    borderRadius: 140,
    backgroundColor: '#DFEFE4',
  },
  bottomRightWave: {
    position: 'absolute',
    right: -80,
    bottom: -90,
    width: 210,
    height: 210,
    border: '1px solid #BEE7E1',
    borderRadius: 120,
  },
  logoWrap: {
    position: 'absolute',
    right: 46,
    top: 34,
    alignItems: 'flex-end',
  },
  logoTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1AA69A',
    letterSpacing: 1,
  },
  logoSub: {
    fontSize: 8,
    color: '#5A7E85',
    marginTop: 2,
  },
  badge: {
    alignSelf: 'flex-start',
    fontSize: 10,
    color: '#1AA69A',
    border: '1px solid #CDEEEA',
    backgroundColor: '#F2FBF9',
    paddingTop: 4,
    paddingRight: 10,
    paddingBottom: 4,
    paddingLeft: 10,
    borderRadius: 999,
    marginBottom: 20,
  },
  coverTitleMain: {
    fontSize: 52,
    lineHeight: 1.05,
    color: '#083A46',
    fontWeight: 'bold',
  },
  coverTitleAccent: {
    fontSize: 52,
    lineHeight: 1.05,
    color: '#1AA69A',
    fontWeight: 'bold',
  },
  coverMeta: {
    marginTop: 20,
    fontSize: 12,
    color: '#567981',
  },
  content: {
    paddingTop: 30,
    paddingRight: 28,
    paddingBottom: 30,
    paddingLeft: 28,
    flexDirection: 'column',
    alignItems: 'stretch',
  },
  section: {
    backgroundColor: '#FFFFFF',
    border: '1px solid #DDEAE8',
    borderRadius: 10,
    padding: 14,
    marginBottom: 14,
    flexDirection: 'column',
    alignItems: 'stretch',
  },
  heading: {
    fontSize: 13,
    marginBottom: 8,
    fontWeight: 'bold',
    color: '#0B4956',
  },
  text: {
    fontSize: 10,
    marginBottom: 4,
    color: '#2E5058',
  },
  listItem: {
    fontSize: 10,
    marginLeft: 10,
    marginBottom: 2,
    color: '#2E5058',
  },
  card: {
    border: '1px solid #DDEAE8',
    backgroundColor: '#FDFEFE',
    borderRadius: 10,
    padding: 10,
    marginBottom: 8,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  avatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    marginRight: 10,
  },

  summaryGrid: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 4,
    marginBottom: 10,
    alignItems: 'stretch',
  },
  summaryCard: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    minWidth: 0,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#D6E5E3',
    backgroundColor: '#FFFFFF',
  },
  summaryStatCardTop: {
    backgroundColor: '#C8E3CB',
    height: 30,
    width: '100%',
  },
  summaryStatCardBody: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 6,
    width: '100%',
  },
  summaryValue: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#0B2E39',
    marginBottom: 4,
    textAlign: 'center',
  },
  summaryLabel: {
    fontSize: 9,
    color: '#2D4D57',
    textAlign: 'center',
    lineHeight: 1.25,
  },
  demoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 4,
  },

  demoThumb: {
    width: 320,
    height: 440,
    borderRadius: 6,
    border: '1px solid #DDEAE8',
    marginRight: 8,
    marginBottom: 12,
  },
  demoLabel: {
    fontSize: 11,
    lineHeight: 1.35,
    color: '#5C7C84',
    marginTop: 8,
  },
  image: {
    width: 400,
    height: 400,
    marginVertical: 15,
    marginHorizontal: 100,
  },
  /** PDF demographics: profile + analytics (first page per influencer) */
  demoTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#0B4956',
    marginBottom: 6,
    textAlign: 'center',
  },
  demoSubtitle: {
    fontSize: 10,
    color: '#5C7C84',
    marginBottom: 14,
    textAlign: 'center',
  },
  demoProfileColumn: {
    width: '100%',
    flexDirection: 'column',
    alignItems: 'center',
  },
  demoProfileImage: {
    width: 120,
    height: 120,
    borderRadius: 60,
    border: '1px solid #DDEAE8',
    objectFit: 'cover',
  },
  demoProfilePlaceholder: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#DDEAE8',
    border: '1px solid #C5D9D4',
  },
  demoAnalyticsHeading: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#0B4956',
    marginTop: 6,
    marginBottom: 8,
    textAlign: 'center',
  },
  demoAnalyticsColumn: {
    width: '100%',
    maxWidth: 320,
    alignSelf: 'center',
    flexDirection: 'column',
    alignItems: 'stretch',
  },
  demoAnalyticsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 6,
    paddingHorizontal: 10,
    marginBottom: 4,
    borderBottom: '1px solid #E8F2EF',
  },
  demoAnalyticsLabel: {
    fontSize: 10,
    color: '#5C7C84',
  },
  demoAnalyticsValue: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#0B4956',
  },
  /** Campaign demographics gallery: up to 3 images per page, centered */
  demoGalleryTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#0B4956',
    marginBottom: 12,
    textAlign: 'center',
  },
  demoGalleryImage: {
    width: 236,
    height: 400,
    marginHorizontal: 8,
    borderRadius: 8,
    border: '1px solid #DDEAE8',
    objectFit: 'cover',
  },
  /** Demographics image pages: outer frame + tall white panel (~full landscape page) */
  demographicsPageFrame: {
    width: '100%',
    minHeight: 560,
    paddingTop: 16,
    paddingRight: 16,
    paddingBottom: 16,
    paddingLeft: 16,
    flexDirection: 'column',
  },
  sectionDemographicsFull: {
    flexGrow: 1,
    minHeight: 528,
    backgroundColor: '#FFFFFF',
    border: '1px solid #DDEAE8',
    borderRadius: 10,
    padding: 16,
    flexDirection: 'column',
    alignItems: 'stretch',
  },
  demoGalleryBody: {
    flexGrow: 1,
    minHeight: 420,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
  },
  demoGalleryRowCentered: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    flexWrap: 'nowrap',
  },

  /** Demographics screenshots inside a phone-style frame (Reel insights mock) */
  demoPhoneWrap: {
    marginHorizontal: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  demoPhoneBezel: {
    width: 200,
    backgroundColor: '#0D0D0D',
    borderRadius: 28,
    paddingTop: 10,
    paddingRight: 9,
    paddingBottom: 9,
    paddingLeft: 9,
    borderWidth: 2,
    borderStyle: 'solid',
    borderColor: '#000000',
    flexDirection: 'column',
    alignItems: 'center',
  },
  demoPhoneEarpiece: {
    width: 48,
    height: 5,
    borderRadius: 3,
    backgroundColor: '#1A1A1A',
    marginBottom: 6,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#2A2A2A',
  },
  demoPhoneScreenShell: {
    borderRadius: 22,
    overflow: 'hidden',
    backgroundColor: '#000000',
    flexDirection: 'column',
    width: '100%',
  },
  demoPhoneStatusBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 7,
    paddingHorizontal: 8,
    backgroundColor: '#121212',
  },
  demoPhoneStatusChevron: {
    fontSize: 14,
    color: '#F5F5F5',
    fontWeight: 'bold',
    width: 22,
  },
  demoPhoneStatusTitle: {
    fontSize: 8,
    color: '#FFFFFF',
    fontWeight: 'bold',
    letterSpacing: 0.2,
    flexGrow: 1,
    textAlign: 'center',
  },
  demoPhoneStatusMore: {
    fontSize: 11,
    color: '#F5F5F5',
    width: 22,
    textAlign: 'right',
    letterSpacing: 1,
  },
  /** Thin accent under nav (matches Reel insights reference) */
  demoPhoneProgressBar: {
    width: '100%',
    height: 3,
    backgroundColor: '#FF3B8D',
  },
  /** Viewport: letterbox so full screenshot is visible (no top crop like cover) */
  demoPhoneScreen: {
    width: 182,
    height: 312,
    backgroundColor: '#000000',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 6,
    paddingBottom: 6,
    paddingHorizontal: 5,
  },
  demoGalleryImageInPhone: {
    width: 172,
    height: 300,
    objectFit: 'contain',
  },
  demoPhoneHomeRow: {
    backgroundColor: '#000000',
    paddingTop: 6,
    paddingBottom: 8,
    alignItems: 'center',
  },
  demoPhoneHomeBar: {
    width: 44,
    height: 3,
    borderRadius: 2,
    backgroundColor: '#3A3A3A',
  },

  /** Thank You — final PDF page (white, teal bar, corner decorations) */
  thankYouPage: {
    backgroundColor: '#FFFFFF',
    paddingTop: 36,
    paddingRight: 40,
    paddingBottom: 36,
    paddingLeft: 40,
    position: 'relative',
    overflow: 'hidden',
    flexDirection: 'column',
    justifyContent: 'space-between',
    minHeight: '100%',
  },
  thankYouDecorLayer: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },
  thankYouCornerSquare: {
    position: 'absolute',
    width: 10,
    height: 10,
    backgroundColor: '#000000',
  },
  thankYouCornerSquareTL: {
    top: 22,
    left: 22,
  },
  thankYouCornerSquareBR: {
    bottom: 28,
    right: 28,
  },
  thankYouMintBlock: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    width: 28,
    height: 100,
    backgroundColor: '#C8E6C9',
  },
  thankYouHalftoneWrap: {
    position: 'absolute',
    top: 14,
    left: 14,
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: 72,
  },
  thankYouHalftoneDot: {
    width: 3,
    height: 3,
    borderRadius: 1.5,
    marginRight: 5,
    marginBottom: 5,
    backgroundColor: '#D0D0D0',
  },
  thankYouHalftoneWrapBR: {
    position: 'absolute',
    bottom: 18,
    right: 56,
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: 64,
    justifyContent: 'flex-end',
  },
  thankYouDotGridWrap: {
    position: 'absolute',
    width: 40,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  thankYouDotGridTR: {
    top: 20,
    right: 20,
  },
  thankYouDotGridBL: {
    bottom: 24,
    left: 20,
  },
  thankYouBlackMiniDot: {
    width: 4,
    height: 4,
    backgroundColor: '#000000',
    marginRight: 5,
    marginBottom: 5,
  },
  thankYouMain: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 24,
    paddingBottom: 16,
    zIndex: 1,
  },
  thankYouHeading: {
    fontSize: 44,
    fontWeight: 'bold',
    color: '#000000',
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  thankYouRule: {
    width: 220,
    height: 1,
    backgroundColor: '#000000',
    marginTop: 10,
    marginBottom: 14,
  },
  thankYouSub: {
    fontSize: 9,
    fontWeight: 'normal',
    color: '#000000',
    textAlign: 'center',
    letterSpacing: 1.4,
    textTransform: 'uppercase',
    maxWidth: 520,
    lineHeight: 1.45,
  },
  thankYouTealRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    marginTop: 14,
    paddingHorizontal: 8,
  },
  thankYouTealSpacer: {
    width: '38%',
  },
  thankYouTealBar: {
    flexGrow: 1,
    height: 14,
    backgroundColor: '#008B7D',
  },
  thankYouFooter: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: 8,
    zIndex: 1,
  },
  thankYouLogoGif: {
    width: 160,
    height: 72,
    objectFit: 'contain',
  },
  thankYouBrand: {
    marginTop: 10,
    fontSize: 14,
    fontWeight: 'bold',
    color: '#1AA69A',
    letterSpacing: 0.8,
  },
  thankYouBrandSub: {
    marginTop: 2,
    fontSize: 7,
    color: '#5A7E85',
    letterSpacing: 0.3,
  },
});
