import { StyleSheet } from '@react-pdf/renderer';
export const styles = StyleSheet.create({
  page: {
    backgroundColor: '#F7FBFA',
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
  },
  fullWidth: {
    width: '100%',
  },
  cover: {
    minHeight: '100%',
    backgroundColor: '#FFFFFF',
    paddingTop: 56,
    paddingRight: 48,
    paddingBottom: 56,
    paddingLeft: 48,
    borderBottom: '6px solid #1AA69A',
    justifyContent: 'space-between',
    position: 'relative',
    overflow: 'hidden',
  },
  topWave: {
    position: 'absolute',
    top: -120,
    left: -80,
    width: 320,
    height: 320,
    border: '2px solid #9ED7CF',
    borderRadius: 180,
  },
  topWaveInner: {
    position: 'absolute',
    top: -90,
    left: -50,
    width: 260,
    height: 260,
    border: '1px solid #BEE7E1',
    borderRadius: 140,
  },
  bottomBlob: {
    position: 'absolute',
    bottom: -110,
    left: -90,
    width: 240,
    height: 240,
    borderRadius: 140,
    backgroundColor: '#DFEFE4',
  },
  bottomRightWave: {
    position: 'absolute',
    right: -80,
    bottom: -90,
    width: 210,
    height: 210,
    border: '1px solid #BEE7E1',
    borderRadius: 120,
  },
  logoWrap: {
    position: 'absolute',
    right: 46,
    top: 34,
    alignItems: 'flex-end',
  },
  logoTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1AA69A',
    letterSpacing: 1,
  },
  logoSub: {
    fontSize: 8,
    color: '#5A7E85',
    marginTop: 2,
  },
  badge: {
    alignSelf: 'flex-start',
    fontSize: 10,
    color: '#1AA69A',
    border: '1px solid #CDEEEA',
    backgroundColor: '#F2FBF9',
    paddingTop: 4,
    paddingRight: 10,
    paddingBottom: 4,
    paddingLeft: 10,
    borderRadius: 999,
    marginBottom: 20,
  },
  coverTitleMain: {
    fontSize: 52,
    lineHeight: 1.05,
    color: '#083A46',
    fontWeight: 'bold',
  },
  coverTitleAccent: {
    fontSize: 52,
    lineHeight: 1.05,
    color: '#1AA69A',
    fontWeight: 'bold',
  },
  coverMeta: {
    marginTop: 20,
    fontSize: 12,
    color: '#567981',
  },
  content: {
    paddingTop: 30,
    paddingRight: 28,
    paddingBottom: 30,
    paddingLeft: 28,
    flexDirection: 'column',
    alignItems: 'stretch',
  },
  section: {
    backgroundColor: '#FFFFFF',
    border: '1px solid #DDEAE8',
    borderRadius: 10,
    padding: 14,
    marginBottom: 14,
    flexDirection: 'column',
    alignItems: 'stretch',
  },
  heading: {
    fontSize: 13,
    marginBottom: 8,
    fontWeight: 'bold',
    color: '#0B4956',
  },
  text: {
    fontSize: 10,
    marginBottom: 4,
    color: '#2E5058',
  },
  listItem: {
    fontSize: 10,
    marginLeft: 10,
    marginBottom: 2,
    color: '#2E5058',
  },
  card: {
    border: '1px solid #DDEAE8',
    backgroundColor: '#FDFEFE',
    borderRadius: 10,
    padding: 10,
    marginBottom: 8,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  avatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    marginRight: 10,
  },
  summaryGrid: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 10,
  },
  summaryCard: {
    flex: 1,
    border: '1px solid #DDEAE8',
    borderRadius: 8,
    padding: 8,
    backgroundColor: '#FFFFFF',
  },
  summaryLabel: {
    fontSize: 9,
    color: '#5C7C84',
  },
  summaryValue: {
    marginTop: 2,
    fontSize: 14,
    fontWeight: 'bold',
    color: '#0B4956',
  },
  demoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 4,
  },

  demoThumb: {
    width: 320,
    height: 440,
    borderRadius: 6,
    border: '1px solid #DDEAE8',
    marginRight: 8,
    marginBottom: 12,
  },
  demoLabel: {
    fontSize: 11,
    lineHeight: 1.35,
    color: '#5C7C84',
    marginTop: 8,
  },
  image: {
    width: 400,
    height: 400,
    marginVertical: 15,
    marginHorizontal: 100,
  },
  /** PDF demographics: profile + analytics (first page per influencer) */
  demoTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#0B4956',
    marginBottom: 6,
    textAlign: 'center',
  },
  demoSubtitle: {
    fontSize: 10,
    color: '#5C7C84',
    marginBottom: 14,
    textAlign: 'center',
  },
  demoProfileColumn: {
    width: '100%',
    flexDirection: 'column',
    alignItems: 'center',
  },
  demoProfileImage: {
    width: 120,
    height: 120,
    borderRadius: 60,
    border: '1px solid #DDEAE8',
    objectFit: 'cover',
  },
  demoProfilePlaceholder: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#DDEAE8',
    border: '1px solid #C5D9D4',
  },
  demoAnalyticsHeading: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#0B4956',
    marginTop: 6,
    marginBottom: 8,
    textAlign: 'center',
  },
  demoAnalyticsColumn: {
    width: '100%',
    maxWidth: 320,
    alignSelf: 'center',
    flexDirection: 'column',
    alignItems: 'stretch',
  },
  demoAnalyticsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 6,
    paddingHorizontal: 10,
    marginBottom: 4,
    borderBottom: '1px solid #E8F2EF',
  },
  demoAnalyticsLabel: {
    fontSize: 10,
    color: '#5C7C84',
  },
  demoAnalyticsValue: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#0B4956',
  },
  /** Campaign demographics gallery: up to 3 images per page, centered */
  demoGalleryTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#0B4956',
    marginBottom: 12,
    textAlign: 'center',
  },
  demoGalleryImage: {
    width: 236,
    height: 400,
    marginHorizontal: 8,
    borderRadius: 8,
    border: '1px solid #DDEAE8',
    objectFit: 'cover',
  },
  /** Demographics image pages: outer frame + tall white panel (~full landscape page) */
  demographicsPageFrame: {
    width: '100%',
    minHeight: 560,
    paddingTop: 16,
    paddingRight: 16,
    paddingBottom: 16,
    paddingLeft: 16,
    flexDirection: 'column',
  },
  sectionDemographicsFull: {
    flexGrow: 1,
    minHeight: 528,
    backgroundColor: '#FFFFFF',
    border: '1px solid #DDEAE8',
    borderRadius: 10,
    padding: 16,
    flexDirection: 'column',
    alignItems: 'stretch',
  },
  demoGalleryBody: {
    flexGrow: 1,
    minHeight: 420,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
  },
  demoGalleryRowCentered: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
});
