export const campaignNames = [
  'Fashion',
  'Beauty',
  'Skin Care',
  'Food',
  'Travel',
  'Lifestyle',
  'Technology',
  'Sports',
  'Music',
  'Gaming',
  'Education',
  'Health',
  'Finance',
  'Real Estate',
  'Automotive',
  'Pets',
  'Fitness',
  'Art',
  'Photography',
  'Movies',
  'Parenting',
  'Environment',
  'Politics',
  'Science',
  'History',
];

export const getCategoryIcon = (name: string) => {
  const icons: { [key: string]: string } = {
    'Fashion': '👗',
    'Beauty': '💄',
    'Skin Care': '🧴',
    'Food': '🍕',
    'Travel': '✈️',
    'Lifestyle': '🌟',
    'Technology': '💻',
    'Sports': '⚽',
    'Music': '🎵',
    'Gaming': '🎮',
    'Education': '📚',
    'Health': '💪',
    'Finance': '💰',
    'Real Estate': '🏠',
    'Automotive': '🚗',
    'Pets': '🐕',
    'Fitness': '🏋️',
    'Art': '🎨',
    'Photography': '📸',
    'Movies': '🎬',
    'Parenting': '👨‍👩‍👧',
    'Environment': '🌍',
    'Politics': '🏛️',
    'Science': '🔬',
    'History': '📜',
  };
  return icons[name] || '📌';
};
